### ISSUE TITLE
fetch: easy performance improvements when uploading to cloud stores

### ISSUE THREAD

**Issue by otan** [cockroachdb/molt#14]
We currently are missing the following performance recommendations for fetch which I think would be useful:

* [x] We currently only break files down after it reaches a certain size. We should also give the option to "split" files by number of rows as well. That would be around here: https://github.com/cockroachdb/molt/blob/53f0b01025f56c8060620fb2d2c6291b47df2b5f/fetch/csv_pipe.go#L72
* [x] We should zip files whilst piping to the data store by writing the file through a `gzip` Writer object in `CSVPipe`: https://pkg.go.dev/compress/gzip - this should be optional (--compression gzip/bzip/none), defaulting to gzip. When calling `IMPORT` on CockroachDB, use `decompress` as well: https://www.cockroachlabs.com/docs/stable/import#import-options

**Comment by ryanluu12345** [comment]
Ideas for breaking down files after num rows: 
- Keep track of the current rows in the csvPipe struct: `curNumRows`. If this number exceeds a certain number, we flush.
- We should add a flag like: `--flush-after-num-rows`

Ideas for gzip:
- Write the CSV items to a separate gzip or compressed writer
- Use that writer to write the record instead
- Update the import to use the `decompress` option
- These are both turned on conditionally based on the flag being passed in

**Comment by ryanluu12345** [comment]
PR to address item 1: https://github.com/cockroachdb/molt/pull/31/files

**Comment by ryanluu12345** [comment]
@otan agreed. It was auto-closed because I referenced the issue number in the PR.
