### ISSUE TITLE
fetch: show/measure IMPORT progress 

### ISSUE THREAD

**Issue by otan** [cockroachdb/molt#15]
Today, when we run IMPORT, there is no indication of progress - we don't log # of rows imported, and we don't display it on prometheus. That's because the SQL command for IMPORT blocks.

To get around this, we'd need to run `SHOW JOBS` and select the job performing the import periodically.

**Comment by ryanluu12345** [comment]
Looked at `SHOW JOBS` and it gives us a fraction completed. We can just query that in a go routine while the import is going on. Can probably spin off another go routine inside of that block and log it back out the user on CLI.

**Comment by otan** [comment]
the trickiness is knowing which import belongs to who; each import table is a separate job

**Comment by ryanluu12345** [comment]
What is most tricky about this? Does each fetch run spawn multiple import jobs concurrently? And in that case, do we report on each job's progress?

**Comment by otan** [comment]
you may have multiple tables spawned at once. you'll have to parse the show jobs statement somehow and make sure the tables are the same
