### ISSUE TITLE
MOLT Verify logs show passwords in connection string

### ISSUE THREAD

**Issue by cotedm** [cockroachdb/molt#2]
MOLT Verify shows the password via the connection string in logging. We should redact this information:

<nil> INF connecting to postgres://postgres:mysecretpassword@localhost:5432/test
<nil> INF connected to postgres://postgres:mysecretpassword@localhost:5432/test as pg_truth
<nil> INF connecting to postgresql://root@localhost:26257/defaultdb?sslmode=disable
<nil> INF connected to postgresql://root@localhost:26257/defaultdb?sslmode=disable as crdb_compare
<nil> INF verification in progress

**Comment by otan** [comment]
resolved in newer version
